### ISSUE TITLE
Using with Adafruit Motor Hat

### ISSUE THREAD

**Issue by robreuss** [Kaiede/PCA9685#2]
The AdaFruit Motor Hat makes use of the PCA9685.  I'd love to be able to use your library to control it but I'm having a bit of trouble.  The Motor Hat's I2C address is 0x60, not 0x40.  Is there anyway to work around this difference?

**Comment by robreuss** [comment]
I went ahead, forked and simply changed the hard-coded address to 0x60 and things are working!  I've been really struggling to port the AdaFruit Motor Hat library so your work is a godsend.  Thank you.

**Comment by Kaiede** [comment]
Apologies, since I didn't see this until just now. 

Disappointing that they use a different address, but the library is built to handle this sort of funny business, since the Adafruit HAT I'm using is meant to be stackable, I just never changed it from the super basic definition:

```
public enum Address: UInt8 {
    case pca9685     = 0x40
}
```

I've been aiming at keeping things type safe when possible. Either the Address parameter should really just be a UInt8, or we can add known addresses to this enum for the known HATs.

**Comment by robreuss** [comment]
Thanks again for super-helpful piece of software!

**Comment by Kaiede** [comment]
I'm actually going to leave this open, since it should be possible to use the library for non-default addresses, and I want to use this to track that change.

**Comment by Kaiede** [comment]
This is fixed up in 2.0.3 now.

Address is now a UInt8, like it should be, and PCA9685.defaultAdafruitAddress is where 0x40 is stored.
